import { checkCloudForNewer } from './lib/storage.js';

const $=s=>document.querySelector(s);
function api(path,options={}){return fetch(path,{credentials:'same-origin',cache:'no-store',...options,headers:{...(options.body?{'Content-Type':'application/json'}:{}),...(options.headers||{})}}).then(async r=>{let j=null;try{j=await r.json()}catch{}if(!r.ok)throw new Error(j?.error||`Request failed (${r.status}).`);return j;});}
function msg(sel,text,type=''){const el=$(sel);if(!el)return;el.className=`account-message ${type}`.trim();el.textContent=text;}

function styles(){if($('#fitquestAccountStyles'))return;const s=document.createElement('style');s.id='fitquestAccountStyles';s.textContent=`
.account-toolbar-button,.sync-chip{min-height:40px;border-radius:12px;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.055);color:inherit;padding:0 12px;font:inherit;font-size:12px;font-weight:800;white-space:nowrap}.account-toolbar-button{cursor:pointer}.sync-chip{color:#a9b7d0}.sync-chip[data-state=saving],.sync-chip[data-state=loading]{color:#ffe28b}.sync-chip[data-state=synced]{color:#7ef0bc}.sync-chip[data-state=error]{color:#ff9da7}.sync-chip[data-state=remote]{color:#ffd57c;cursor:pointer}
#accountDialog,#resetPasswordDialog{width:min(92vw,560px);border:1px solid rgba(255,255,255,.13);border-radius:24px;background:#0f1629;color:#f7f8ff;padding:0;box-shadow:0 30px 90px rgba(0,0,0,.55)}#accountDialog::backdrop,#resetPasswordDialog::backdrop{background:rgba(1,4,12,.78);backdrop-filter:blur(5px)}.account-dialog-body{padding:24px;display:grid;gap:20px}.account-dialog-head{display:flex;justify-content:space-between;align-items:flex-start;gap:16px}.account-dialog-head h3{margin:3px 0 0}.account-section{display:grid;gap:12px;padding:16px;border-radius:18px;border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.035)}.account-section h4{margin:0}.account-section label{display:grid;gap:7px;font-size:13px;font-weight:750}.account-section input{width:100%;box-sizing:border-box;min-height:46px;border-radius:12px;border:1px solid rgba(255,255,255,.12);background:#080d19;color:#fff;padding:0 13px;font:inherit}.account-row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.account-email{font-weight:800;word-break:break-all}.account-badge{display:inline-flex;align-items:center;min-height:30px;border-radius:999px;padding:0 10px;font-size:11px;font-weight:900;background:rgba(255,255,255,.06);color:#a9b7d0}.account-badge.verified{color:#72eab4}.account-message{min-height:18px;margin:0;color:#a9b7d0;font-size:13px;line-height:1.5}.account-message.error{color:#ff9da7}.account-message.success{color:#72eab4}.danger-account{border-color:rgba(255,110,120,.25)}.danger-account button{border-color:rgba(255,110,120,.28);color:#ff9da7}.forgot-link{display:block;margin:-4px auto 8px;border:0;background:transparent;color:#9faefc;font:inherit;font-size:13px;font-weight:800;cursor:pointer}@media(max-width:720px){.sync-chip{display:none}}
`;document.head.appendChild(s);}

function toolbar(){const a=$('.header-actions');if(!a)return;if(!$('#fitquestSyncChip')){const c=document.createElement('button');c.id='fitquestSyncChip';c.type='button';c.className='sync-chip';c.textContent='☁ Cloud';a.insertBefore(c,$('#logoutBtn')||$('#levelChip')||null);}if(!$('#accountBtn')){const b=document.createElement('button');b.id='accountBtn';b.type='button';b.className='account-toolbar-button';b.textContent='👤 Account';a.insertBefore(b,$('#logoutBtn')||$('#levelChip')||null);b.addEventListener('click',openAccount);}}
function forgot(){if($('#forgotPasswordBtn')||!$('#loginForm'))return;const b=document.createElement('button');b.id='forgotPasswordBtn';b.type='button';b.className='forgot-link';b.textContent='Forgot password?';const submit=$('#loginForm .auth-submit');submit?submit.insertAdjacentElement('afterend',b):$('#loginForm').appendChild(b);b.addEventListener('click',requestReset);}

function dialogs(){if(!$('#accountDialog')){const d=document.createElement('dialog');d.id='accountDialog';d.innerHTML=`<div class="account-dialog-body"><div class="account-dialog-head"><div><p class="eyebrow">PLAYER ACCOUNT · CLOUD IDENTITY</p><h3>Account & Security</h3></div><button type="button" class="icon-btn" id="accountCloseBtn">×</button></div><section class="account-section"><h4>Profile</h4><div><div class="account-email" id="accountEmail">—</div><div class="account-row" style="margin-top:8px"><span class="account-badge" id="verificationBadge">Email status</span><button class="ghost mini" id="sendVerificationBtn" type="button">Send verification email</button></div></div><label>Display name<input id="accountDisplayName" maxlength="60" placeholder="Your adventurer name"></label><button class="primary compact" id="saveAccountProfileBtn" type="button">Save Account Profile</button><p class="account-message" id="accountProfileMessage"></p></section><section class="account-section"><h4>Change Password</h4><label>Current password<input id="accountCurrentPassword" type="password" autocomplete="current-password"></label><label>New password<input id="accountNewPassword" type="password" minlength="10" autocomplete="new-password" placeholder="At least 10 characters"></label><button class="ghost" id="changeAccountPasswordBtn" type="button">Change Password</button><p class="account-message" id="accountPasswordMessage"></p></section><section class="account-section danger-account"><h4>Delete Account</h4><p class="account-message">Permanently removes the account and its FitQuest cloud save.</p><button class="ghost" id="deleteAccountBtn" type="button">Delete My Account</button></section></div>`;document.body.appendChild(d);$('#accountCloseBtn').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d)d.close();});$('#saveAccountProfileBtn').onclick=saveProfile;$('#sendVerificationBtn').onclick=verifyEmail;$('#changeAccountPasswordBtn').onclick=changePassword;$('#deleteAccountBtn').onclick=deleteAccount;}
if(!$('#resetPasswordDialog')){const d=document.createElement('dialog');d.id='resetPasswordDialog';d.innerHTML=`<div class="account-dialog-body"><div class="account-dialog-head"><div><p class="eyebrow">ACCOUNT RECOVERY</p><h3>Choose a New Password</h3></div><button type="button" class="icon-btn" id="resetCloseBtn">×</button></div><section class="account-section"><label>New password<input id="resetNewPassword" type="password" minlength="10" autocomplete="new-password" placeholder="At least 10 characters"></label><button class="primary compact" id="finishResetBtn" type="button">Reset Password</button><p class="account-message" id="resetPasswordMessage"></p></section></div>`;document.body.appendChild(d);$('#resetCloseBtn').onclick=()=>d.close();$('#finishResetBtn').onclick=finishReset;}}

async function openAccount(){const d=$('#accountDialog');d.showModal();msg('#accountProfileMessage','Loading account…');try{const r=await api('/api/account');const a=r.account;$('#accountEmail').textContent=a.email;$('#accountDisplayName').value=a.display_name||'';const v=!!a.email_verified_at,b=$('#verificationBadge');b.textContent=v?'✓ Email verified':'Email not verified';b.classList.toggle('verified',v);$('#sendVerificationBtn').hidden=v;msg('#accountProfileMessage',v?'Account is connected to your cloud save.':'Verify your email to strengthen account recovery.');}catch(e){msg('#accountProfileMessage',e.message,'error');}}
async function saveProfile(){msg('#accountProfileMessage','Saving…');try{await api('/api/account',{method:'PUT',body:JSON.stringify({display_name:$('#accountDisplayName').value.trim()})});msg('#accountProfileMessage','Account profile saved.','success');}catch(e){msg('#accountProfileMessage',e.message,'error');}}
async function verifyEmail(){const b=$('#sendVerificationBtn');b.disabled=true;msg('#accountProfileMessage','Sending verification email…');try{const r=await api('/api/auth/verification/request',{method:'POST'});if(r.already_verified){b.hidden=true;msg('#accountProfileMessage','Email is already verified.','success');}else if(r.delivered)msg('#accountProfileMessage','Verification email sent. Check your inbox.','success');else msg('#accountProfileMessage',r.delivery_error||'Email delivery is not configured yet.','error');}catch(e){msg('#accountProfileMessage',e.message,'error');}finally{b.disabled=false;}}
async function changePassword(){msg('#accountPasswordMessage','Updating password…');try{await api('/api/account/password',{method:'POST',body:JSON.stringify({current_password:$('#accountCurrentPassword').value,new_password:$('#accountNewPassword').value})});$('#accountCurrentPassword').value='';$('#accountNewPassword').value='';msg('#accountPasswordMessage','Password changed. Your current device remains signed in.','success');}catch(e){msg('#accountPasswordMessage',e.message,'error');}}
async function deleteAccount(){if(!confirm('Permanently delete this FitQuest account and its cloud save? This cannot be undone.'))return;if(prompt('Type DELETE to confirm.')!=='DELETE')return;try{await api('/api/account',{method:'DELETE'});location.reload();}catch(e){alert(e.message);}}
async function requestReset(){let email=$('#loginEmail')?.value?.trim()||'';if(!email)email=(prompt('Enter the email address for your FitQuest account:')||'').trim();if(!email)return;const b=$('#forgotPasswordBtn'),old=b.textContent;b.disabled=true;b.textContent='Sending…';try{const r=await api('/api/auth/password/forgot',{method:'POST',body:JSON.stringify({email})});alert(r.delivered===false?(r.delivery_error||r.message):r.message);}catch(e){alert(e.message);}finally{b.disabled=false;b.textContent=old;}}
async function confirmVerify(token){try{await api('/api/auth/verification/confirm',{method:'POST',body:JSON.stringify({token})});alert('Your FitQuest email is verified.');}catch(e){alert(e.message);}const u=new URL(location.href);u.searchParams.delete('verify');history.replaceState({},'',u);}
async function finishReset(){const token=new URL(location.href).searchParams.get('reset');msg('#resetPasswordMessage','Resetting password…');try{await api('/api/auth/password/reset',{method:'POST',body:JSON.stringify({token,new_password:$('#resetNewPassword').value})});msg('#resetPasswordMessage','Password reset. You can sign in with the new password.','success');const u=new URL(location.href);u.searchParams.delete('reset');history.replaceState({},'',u);setTimeout(()=>location.reload(),1200);}catch(e){msg('#resetPasswordMessage',e.message,'error');}}

function syncUI(e){const c=$('#fitquestSyncChip');if(!c)return;const s=e.detail?.status,map={saving:['☁ Saving…','saving'],loading:['☁ Loading…','loading'],synced:['☁ Synced','synced'],error:['☁ Sync error','error'],'signed-out':['Signed out','idle']};if(map[s]){c.textContent=map[s][0];c.dataset.state=map[s][1];c.onclick=null;}}
function remote(){const c=$('#fitquestSyncChip');if(!c)return;c.textContent='☁ New data — reload';c.dataset.state='remote';c.onclick=()=>location.reload();}
function authLinks(){const u=new URL(location.href),v=u.searchParams.get('verify'),r=u.searchParams.get('reset');if(v)void confirmVerify(v);if(r)$('#resetPasswordDialog')?.showModal();}
async function poll(){if(document.hidden)return;try{await checkCloudForNewer();}catch{}}
function install(){styles();toolbar();forgot();dialogs();addEventListener('fitquest:sync',syncUI);addEventListener('fitquest:remote-update',remote);authLinks();setInterval(poll,30000);addEventListener('focus',poll);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
