import { $, read, mutate, ensureRpg, localDateISO, dayMetrics, stats } from './rpgCore.js';
import { evaluateCombos } from './comboSystem.js';
import { evaluateRecords } from './personalRecords.js';
import { ensureQuestBoard, updateQuestBoard, selectQuest } from './questBoard.js';
import { chronicleFor } from './chronicler.js';
import { campaignState } from './campaignMap.js';
import { maybeEncounter } from './randomEncounters.js';
import { grantLoot } from './lootSystem.js';
import { buildDailyReport } from './dailyRecap.js';

let busy=false;
function styles(){ if($('#fqRpgExpansionStyles'))return; const s=document.createElement('style');s.id='fqRpgExpansionStyles';s.textContent=`
.fq-rpg-card{grid-column:1/-1;padding:20px;border-radius:20px;border:1px solid rgba(255,255,255,.08);background:rgba(15,22,41,.94);color:#f4f6ff}.fq-rpg-head{display:flex;justify-content:space-between;gap:12px;align-items:start}.fq-rpg-head p{margin:0;color:#9485ff;font-size:10px;font-weight:900;letter-spacing:.14em}.fq-rpg-head h3{margin:5px 0 0}.fq-rpg-chip{padding:7px 10px;border-radius:999px;background:rgba(255,255,255,.05);font-size:10px;color:#9aa6bd}.fq-quest-grid,.fq-map{display:grid;gap:9px;margin-top:14px}.fq-quest{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center;padding:12px;border-radius:14px;background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.06)}.fq-quest button{border:1px solid rgba(139,111,255,.25);background:rgba(124,90,255,.1);color:#ddd5ff;border-radius:10px;padding:8px;font-weight:800}.fq-map{grid-template-columns:repeat(5,1fr)}.fq-region{padding:12px 8px;text-align:center;border-radius:14px;background:rgba(255,255,255,.035);font-size:10px}.fq-region.locked{opacity:.38}.fq-region span{display:block;font-size:24px;margin-bottom:5px}.fq-report-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:7px;margin-top:13px}.fq-report-grid div{padding:10px;border-radius:12px;background:rgba(255,255,255,.035)}.fq-report-grid small,.fq-report-grid strong{display:block}.fq-report-grid small{font-size:8px;color:#7e8aa3}.fq-report-grid strong{margin-top:3px;font-size:12px}.fq-chronicle{margin-top:13px;padding:13px;border-left:3px solid #8d76ff;background:rgba(133,105,255,.055);border-radius:0 12px 12px 0;color:#aeb9ce;line-height:1.5}.fq-encounter{margin-top:12px;padding:14px;border:1px solid rgba(255,178,86,.18);background:rgba(255,150,70,.06);border-radius:14px}.fq-toast{position:fixed;right:12px;top:90px;z-index:160000;max-width:320px;padding:13px;border-radius:14px;background:#0b1225;border:1px solid rgba(255,255,255,.1);color:white;box-shadow:0 18px 50px #0008}.fq-level-overlay{position:fixed;inset:0;z-index:170000;display:grid;place-items:center;background:#030611dd;backdrop-filter:blur(12px)}.fq-level-card{width:min(90vw,440px);padding:32px;border-radius:28px;text-align:center;background:linear-gradient(145deg,#182344,#0c1227);border:1px solid #8b76ff55;color:white}.fq-level-card b{display:block;font-size:64px;margin:12px}.fq-level-card button{width:100%;padding:13px;border:0;border-radius:13px;background:linear-gradient(135deg,#6e68ff,#ac53ec);color:white;font-weight:900}@media(max-width:720px){.fq-map{grid-template-columns:repeat(2,1fr)}.fq-report-grid{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(s); }
function toast(title,body,icon='✨'){ const e=document.createElement('div');e.className='fq-toast';e.innerHTML=`<strong>${icon} ${title}</strong><div style="margin-top:4px;color:#9da9c0;font-size:12px">${body}</div>`;document.body.appendChild(e);setTimeout(()=>e.remove(),3200); }
function levelCeremony(level){ if(document.querySelector('.fq-level-overlay'))return;const o=document.createElement('div');o.className='fq-level-overlay';o.innerHTML=`<div class="fq-level-card"><div>LEVEL UP</div><b>LVL ${level}</b><p>The campaign expands. New titles, classes, and regions may now be available.</p><button>Continue the Quest</button></div>`;o.querySelector('button').onclick=()=>o.remove();document.body.appendChild(o); }
async function process(source,eventId){ if(busy)return;busy=true;try{let notices=[];await mutate(data=>{const date=localDateISO();const r=ensureRpg(data);r.levelCeremonies||={};const before=Number(r.lastObservedLevel)||stats(data).level;const combos=evaluateCombos(data,date);const records=evaluateRecords(data,date);updateQuestBoard(data,date);chronicleFor(data,date);const encounter=maybeEncounter(data,{source,eventId,date});const nowLevel=stats(data).level;r.lastObservedLevel=nowLevel;if(nowLevel>before&&!r.levelCeremonies[nowLevel]){r.levelCeremonies[nowLevel]=new Date().toISOString();notices.push(['level',nowLevel]);} combos.forEach(c=>notices.push(['combo',c]));records.forEach(rec=>{notices.push(['record',rec]); if(rec.value>0) grantLoot(data,{lootId:'pathfinder-compass',source:rec.name,eventId:`loot:${rec.id}`});});if(encounter)notices.push(['encounter',encounter]);return true;});for(const [type,x] of notices){if(type==='level')levelCeremony(x);if(type==='combo')toast(x.name,'Healthy systems linked. Combo recorded.',x.icon);if(type==='record')toast('NEW RECORD',`${x.name}: ${x.value}`,'🏆');if(type==='encounter')toast(x.name,x.challenge,x.icon);}await render();}catch(e){console.warn('RPG expansion processing failed',e);}finally{busy=false;} }
async function render(){ const data=await read();if(!data)return; const date=localDateISO(), board=ensureQuestBoard(data,date), map=campaignState(data), report=buildDailyReport(data,date), chron=chronicleFor(data,date), r=ensureRpg(data); const pg=$('#fitquestScreenGrid-progress'); if(pg){let c=$('#fqCampaignSystems');if(!c){c=document.createElement('section');c.id='fqCampaignSystems';c.className='fq-rpg-card';pg.prepend(c);} c.innerHTML=`<div class="fq-rpg-head"><div><p>RPG EXPANSION · CHAPTER I</p><h3>Campaign Systems</h3></div><span class="fq-rpg-chip">${(r.inventory||[]).length} loot</span></div><div class="fq-map">${map.regions.map(x=>`<div class="fq-region ${x.unlocked?'':'locked'}"><span>${x.icon}</span><strong>${x.name}</strong><div>${x.unlocked?'UNLOCKED':`LVL ${x.level}`}</div></div>`).join('')}</div><div class="fq-report-grid"><div><small>SETS</small><strong>${report.strengthSets}</strong></div><div><small>STEPS</small><strong>${report.steps.toLocaleString()}</strong></div><div><small>BOSS DAMAGE</small><strong>${report.bossDamage}</strong></div><div><small>COMBOS</small><strong>${report.combos.length}</strong></div></div>${chron?`<div class="fq-chronicle"><strong>${chron.title}</strong><br>${chron.text}</div>`:''}`; }
 const home=$('#fitquestScreenGrid-home'); if(home){let q=$('#fqQuestBoard');if(!q){q=document.createElement('section');q.id='fqQuestBoard';q.className='fq-rpg-card';home.appendChild(q);}q.innerHTML=`<div class="fq-rpg-head"><div><p>DAILY QUEST BOARD</p><h3>Choose Your Side Quests</h3></div><span class="fq-rpg-chip">Optional</span></div><div class="fq-quest-grid">${board.quests.map(x=>`<div class="fq-quest"><span>${x.icon}</span><div><strong>${x.name}</strong><div style="font-size:10px;color:#8995ad">${x.current||0} / ${x.target} ${x.unit}</div></div><button data-fq-quest="${x.id}">${x.completed?'✓ Done':x.selected?'Selected':'Select'}</button></div>`).join('')}</div>`;q.querySelectorAll('[data-fq-quest]').forEach(b=>b.onclick=async()=>{await mutate(d=>{selectQuest(d,b.dataset.fqQuest,date);updateQuestBoard(d,date);return true;});render();}); }
 const enc=(r.encounters||[]).filter(e=>e.date===date&&e.status==='available').at(-1); if(enc&&home){let e=$('#fqEncounter');if(!e){e=document.createElement('section');e.id='fqEncounter';e.className='fq-rpg-card';home.appendChild(e);}e.innerHTML=`<div class="fq-rpg-head"><div><p>RANDOM ENCOUNTER</p><h3>${enc.icon} ${enc.name}</h3></div><span class="fq-rpg-chip">OPTIONAL</span></div><div class="fq-encounter">${enc.challenge}<div style="margin-top:10px"><button id="fqEncounterDone">Complete</button> <button id="fqEncounterSkip">Skip</button></div></div>`;$('#fqEncounterDone').onclick=()=>resolveEncounter(enc.id,true);$('#fqEncounterSkip').onclick=()=>resolveEncounter(enc.id,false);} }
async function resolveEncounter(id,complete){await mutate(data=>{const r=ensureRpg(data),e=(r.encounters||[]).find(x=>x.id===id);if(!e||e.status!=='available')return false;e.status=complete?'completed':'skipped';e.resolvedAt=new Date().toISOString();if(complete)grantLoot(data,{lootId:'iron-flask',source:e.name,eventId:`loot:${e.id}`});return true;});toast(complete?'Encounter Cleared':'Encounter Skipped',complete?'Loot added to your Character inventory.':'No penalty. The road continues.',complete?'⚔️':'↪️');render();}
function boot(){styles();setTimeout(()=>render().catch(()=>{}),1200); const hooks=['adventure-ended','boss-hit','daily-activity-saved','checkin-saved','nutrition-updated','remote-update'];hooks.forEach(name=>window.addEventListener(`fitquest:${name}`,e=>process(name,e.detail?.id||`${name}:${Date.now()}`)));window.addEventListener('fitquest:navigation',()=>render().catch(()=>{}));window.addEventListener('fitquest:rpg-toast',e=>toast(e.detail?.title||'FitQuest',e.detail?.body||'',e.detail?.icon||'✨'));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
